CREATE SCHEMA IF NOT EXISTS `goorm` DEFAULT CHARACTER SET utf8mb4;

GRANT ALL ON *.* TO 'root'@'*' IDENTIFIED BY 'root' WITH GRANT OPTION;
GRANT ALL ON goorm.* TO 'root'@'*';
FLUSH PRIVILEGES;

USE `goorm`;